#pragma once
//#include "BladeII.h"
#include "EventSubsystem.h"
#include "B2MessageInfoCommonStruct.h"
#include "B2MessageInfo.h"
#include "CommonStruct.h"

namespace data_trader
{
	DECLARE_EVENT_CLASS(RequestNickname)
	DECLARE_EVENT_CLASS(RequestGetAccount)
	DECLARE_EVENT_CLASS(RequestGetAccountItem,					int32, int32)
	DECLARE_EVENT_CLASS(RequestGetServerVersion)
	DECLARE_EVENT_CLASS(RequestGetMasterData)
	DECLARE_EVENT_CLASS(RequestGetLatestEventData,				int64)
	DECLARE_EVENT_CLASS(RequestAddItem,							int32, int32, int32)
	DECLARE_EVENT_CLASS(RequestAddCostumeToInventory,			int32)
	DECLARE_EVENT_CLASS(RequestDismantleItems,					const TArray<int64>&)
	DECLARE_EVENT_CLASS(RequestSellItem,						const TArray<int64>&)
	DECLARE_EVENT_CLASS(RequestSellConsumableItem,				int64, int32)
	DECLARE_EVENT_CLASS(RequestConvertData,						int32)
	DECLARE_EVENT_CLASS(RequestConvertItem,						int32, int32)
	DECLARE_EVENT_CLASS(RequestEquipItem,						int32, const TArray<int64>&)
	DECLARE_EVENT_CLASS(RequestUnequipItem,						int32, const TArray<int64>&)
	DECLARE_EVENT_CLASS(RequestLockItem,						const TArray<int64>&)
	DECLARE_EVENT_CLASS(RequestUnlockItem,						const TArray<int64>&)
	DECLARE_EVENT_CLASS(RequestEnhanceItem,						int64, int32, bool, int32)
	DECLARE_EVENT_CLASS(RequestExchangeItemEnhanceLevel,		int64, int64, int32)
	DECLARE_EVENT_CLASS(RequestOpenSealSlotItem,				int64, int32)
	DECLARE_EVENT_CLASS(RequestCarveSealItem,					int64, int32)
	DECLARE_EVENT_CLASS(RequestLevelupItem,						int64, const TArray<int64>&, bool)
	DECLARE_EVENT_CLASS(RequestSurpassItem,						int64, int64)
	DECLARE_EVENT_CLASS(RequestUpgradeItem,						int64)
	DECLARE_EVENT_CLASS(RequestComposeItem,						int64, int64, int32)
	DECLARE_EVENT_CLASS(RequestChangeItemCharacterType,			int64, int32)
	DECLARE_EVENT_CLASS(RequestGetChangeItemCharacterTypeCost,	int64)
	DECLARE_EVENT_CLASS(RequestExtendInventory,					int32, int32)
	DECLARE_EVENT_CLASS(RequestResurrection,					const FString&, int32)
	DECLARE_EVENT_CLASS(RequestStartStage,						FServerStageID, int32, int32, int32, int32, bool, int32, int32, int32)
	DECLARE_EVENT_CLASS(RequestClearStage,						FServerStageID, const FString&, int32, int32, int32, const TArray<b2network::B2KillMonsterInfoPtr>&, int32, bool, int32, int32, b2network::B2ItemSpotSaleOptionPtr, b2network::B2AetherSpotSaleOptionPtr)
	DECLARE_EVENT_CLASS(RequestFailStage,						FServerStageID, const FString&, int32, int32)
	DECLARE_EVENT_CLASS(RequestSweepStage,						FServerStageID, int32, int32, int32, int32, int32)
	DECLARE_EVENT_CLASS(RequestCheckBladePointCharge) 
	DECLARE_EVENT_CLASS(RequestGetItemSurpassCost,				int64)
	DECLARE_EVENT_CLASS(RequestGetItemUpgradeCost,				int64)
	DECLARE_EVENT_CLASS(RequestGetItemComposeCost,				int64, int32)
	DECLARE_EVENT_CLASS(RequestGetActInfo,						int32, int32)
	DECLARE_EVENT_CLASS(RequestGetStageInfo,					FServerStageID)
	DECLARE_EVENT_CLASS(RequestGetMatchStatus)
	DECLARE_EVENT_CLASS(RequestMatchmaking,						int32, int32, int32, bool, const FString&)
	DECLARE_EVENT_CLASS(RequestJoinRoom,						const FString&, int32, int32, TArray<b2network::B2RoomPropertyPtr>&, TArray<b2network::B2RoomCharacterPtr>&, TArray<b2network::B2PresetNumPtr>&)
	DECLARE_EVENT_CLASS(RequestLeaveRoom,						const FString&)
    DECLARE_EVENT_CLASS(RequestRoomKick,						const FString&, int64)
	

	DECLARE_EVENT_CLASS(RequestRoomProperty,					const FString&, TArray<b2network::B2RoomPropertyPtr>&)

	DECLARE_EVENT_CLASS(RequestCancelMatchmaking)
	DECLARE_EVENT_CLASS(RequestMatchResult,						b2network::B2MatchResult, int32, b2network::B2RoomCharacterPtr, b2network::B2RoomCharacterPtr, b2network::B2RoomCharacterPtr, b2network::B2RoomCharacterPtr, const FString&, bool)

	DECLARE_EVENT_CLASS(RequestRoomClose,						const FString&, int32, int32)
	DECLARE_EVENT_CLASS(RequestRoomLeaveResult,					const FString&, int64, const FString&)
	DECLARE_EVENT_CLASS(RequestRoomAccessControl,				const FString&, int32)
	DECLARE_EVENT_CLASS(RequestReportUserViaChannel,			int64, int32, int32, const FString&)
	DECLARE_EVENT_CLASS(RequestJoinWorld,						const FString&)
	DECLARE_EVENT_CLASS(RequestLeaveWorld,						const FString&)

    DECLARE_EVENT_CLASS(RequestLevelUpSkill,					int32, int32)
    DECLARE_EVENT_CLASS(RequestResetSkill,						int32)
    DECLARE_EVENT_CLASS(RequestBuySkillPoint,					const TArray<b2network::B2BuySkillPointRequestInfoPtr>&)
    DECLARE_EVENT_CLASS(RequestSetUsingSkill,					int32, int32, int32, int32, int32)
	DECLARE_EVENT_CLASS(RequestReceiveActRepeatClearReward,		int32, int32)
	DECLARE_EVENT_CLASS(RequestReceiveActClearReward,			int32, int32, int32)
	DECLARE_EVENT_CLASS(RequestGetTeamBattleStatus)
	DECLARE_EVENT_CLASS(RequestUpdateTeamBattleEntry,			b2network::B2TeamBattleEntryPtr)
	DECLARE_EVENT_CLASS(RequestEnhanceTeamBattleFormation,		int32)	
	DECLARE_EVENT_CLASS(RequestTeamMatchmaking,					bool)
	DECLARE_EVENT_CLASS(RequestTeamMatchResult,					const FString&, int32, bool)
	DECLARE_EVENT_CLASS(RequestRaidMatchmaking,					int32, int32, int32, int32, b2network::B2EndpointPtr)
	DECLARE_EVENT_CLASS(RequestRoomInvitation,					const FString&, const FString&, int32, int32, int32)
    DECLARE_EVENT_CLASS(RequestGetRank)
	DECLARE_EVENT_CLASS(RequestEnhanceRankNode,					int32)
	DECLARE_EVENT_CLASS(RequestActivateRankNode,				int32)
	DECLARE_EVENT_CLASS(RequestSetCharNickName,					int32, const FString&)
	DECLARE_EVENT_CLASS(RequestGetMailList,						int32)
	DECLARE_EVENT_CLASS(RequestOpenMail,						int64, int32, int32, int32)
	DECLARE_EVENT_CLASS(RequestOpenAllMail,						int32, int64, int64)
	DECLARE_EVENT_CLASS(RequestGetNewMailCount)
	DECLARE_EVENT_CLASS(RequestAddMail,						    int32, int32, int32, int32, int32, int32, int32, int32, int32, int32, int32)
	DECLARE_EVENT_CLASS(RequestGetChatChannel)
	DECLARE_EVENT_CLASS(RequestChangeChatChannel,				int32)
	DECLARE_EVENT_CLASS(RequestAskFriend,						int64)
	DECLARE_EVENT_CLASS(RequestAcceptAskFriend,					int64)
	DECLARE_EVENT_CLASS(RequestRejectAskFriend,					int64)
	DECLARE_EVENT_CLASS(RequestGetFriendList)
	DECLARE_EVENT_CLASS(RequestCancelAskFriend,					int64)
	DECLARE_EVENT_CLASS(RequestDeleteFriend,					int64)
	DECLARE_EVENT_CLASS(RequestGetAllSendAskFriend)
	DECLARE_EVENT_CLASS(RequestGetAllReceiveAskFriend)
	DECLARE_EVENT_CLASS(RequestSendSocialPoint,					TArray<int64>)
	DECLARE_EVENT_CLASS(RequestConfirmNewFriend,				bool, TArray<int64>)
	DECLARE_EVENT_CLASS(RequestGetRecommendFriend)
	DECLARE_EVENT_CLASS(RequestPlatformFriendInviteInfo,		int32)
	DECLARE_EVENT_CLASS(RequestPlatformFriendInviteCountUp,		int32)
	DECLARE_EVENT_CLASS(RequestPlatformFriendJoinerCountUp,		int32, int32)
	DECLARE_EVENT_CLASS(RequestPlatformFriendInviteReward,		int32, int32, int32)
	DECLARE_EVENT_CLASS(RequestFindUser,						const FString&, bool)
	DECLARE_EVENT_CLASS(RequestGetQuest)
	DECLARE_EVENT_CLASS(RequestAcceptQuest,						int32)
	DECLARE_EVENT_CLASS(RequestReceiveQuestReward,				int32)
	DECLARE_EVENT_CLASS(RequestGetCounterDungeon)
	DECLARE_EVENT_CLASS(RequestStartCounterDungeon,				FServerStageID, int32)
	DECLARE_EVENT_CLASS(RequestForceStartCounterDungeon,		FServerStageID)
	DECLARE_EVENT_CLASS(RequestFinishCounterDungeon,			FServerStageID, const FString&, bool, bool)
	DECLARE_EVENT_CLASS(RequestSweepCounterDungeon,				FServerStageID, int32)
	DECLARE_EVENT_CLASS(RequestBuyCounterDungeonTicket)
	DECLARE_EVENT_CLASS(RequestCounterDungeonWeeklyReward,		int32)
	DECLARE_EVENT_CLASS(RequestGetDimension)
	DECLARE_EVENT_CLASS(RequestStartDimension,					int32, int32, int32, int32)
	DECLARE_EVENT_CLASS(RequestFinishDimension,					int32, const FString&, int32, int32)
	DECLARE_EVENT_CLASS(RequestCreateGuild,						const FString&, int32, int32, int32, int32, int32)
	DECLARE_EVENT_CLASS(RequestAskJoinGuild,					int64)
	DECLARE_EVENT_CLASS(RequestLeaveGuild)
	DECLARE_EVENT_CLASS(RequestGetGuildDetailInfo,				int64)
	DECLARE_EVENT_CLASS(RequestGetGuildMember)
	DECLARE_EVENT_CLASS(RequestDeleteGuild)
	DECLARE_EVENT_CLASS(RequestGetRecommendGuild)
	DECLARE_EVENT_CLASS(RequestAppointSubGuildMaster,			int64) 
	DECLARE_EVENT_CLASS(RequestDismissSubGuildMaster,			int64)
	DECLARE_EVENT_CLASS(RequestKickGuildMember,					int64)
	DECLARE_EVENT_CLASS(RequestUpdateGuild,						int32, int32, int32, int32, int32)
	DECLARE_EVENT_CLASS(RequestUpdateGuildNotice,				const FString&)
	DECLARE_EVENT_CLASS(RequestGetGuildMemberCandidates,		bool)
	DECLARE_EVENT_CLASS(RequestInviteGuild,						int64)
	DECLARE_EVENT_CLASS(RequestGetGuildInviteList)
	DECLARE_EVENT_CLASS(RequestRejectInviteGuild,				int64)
	DECLARE_EVENT_CLASS(RequestAcceptInviteGuild,				int64)
	DECLARE_EVENT_CLASS(RequestFindGuild,						const FString&)
	DECLARE_EVENT_CLASS(RequestObtainGuildMaster)
	DECLARE_EVENT_CLASS(RequestHandOverGuildMaster,				int64)
	DECLARE_EVENT_CLASS(RequestGetGuildRankingList)
	DECLARE_EVENT_CLASS(RequestLevelUpGuildSkill,				int32)
	DECLARE_EVENT_CLASS(RequestBuyGuildSkill,					int32, int32)
	DECLARE_EVENT_CLASS(RequestGetMission,						int32)
	DECLARE_EVENT_CLASS(RequestGetFeaturedMission)
	DECLARE_EVENT_CLASS(RequestReceiveMissionReward,			int32)
	DECLARE_EVENT_CLASS(RequestReceiveCompleteMissionReward,	int32, int32)
	DECLARE_EVENT_CLASS(RequestGetWing,						    int32)
	DECLARE_EVENT_CLASS(RequestEnhanceWing,					    int32)
	DECLARE_EVENT_CLASS(RequestUpgradeWing,						int32)
	DECLARE_EVENT_CLASS(RequestEnhanceWingOption,				int32, int32)
	DECLARE_EVENT_CLASS(RequestGetDonationEvent)
	DECLARE_EVENT_CLASS(RequestMakeDonation,					int32, bool, bool, bool, const FString&)
	DECLARE_EVENT_CLASS(RequestDonationPointReward,				int32, int32)
	DECLARE_EVENT_CLASS(RequestGetFairy)
	DECLARE_EVENT_CLASS(RequestLevelupFairy,					int32)
	DECLARE_EVENT_CLASS(RequestBlessFairy,						int32, int32)
	DECLARE_EVENT_CLASS(RequestReceiveFairyGift,				int32)
	DECLARE_EVENT_CLASS(RequestGetHeroTower)
	DECLARE_EVENT_CLASS(RequestStartHeroTower,					int32, int32, int32, const FString&)
	DECLARE_EVENT_CLASS(RequestFinishHeroTower,					int32, const FString&, int32, bool)
	DECLARE_EVENT_CLASS(RequestAbandonHeroTower,				int32, const FString&)
	DECLARE_EVENT_CLASS(RequestSweepHeroTower)
	DECLARE_EVENT_CLASS(RequestBuyHeroTowerTicket)
	DECLARE_EVENT_CLASS(RequestEnhanceRelic,					int32, int32)
	DECLARE_EVENT_CLASS(RequestPromotionRelic,					int32, int32)
	DECLARE_EVENT_CLASS(RequestGetAccountRelic,					int32)
	DECLARE_EVENT_CLASS(RequestDrawShopLottery,					int32, int32, bool, bool, const FString&, bool)
	DECLARE_EVENT_CLASS(RequestRewardShopMileage,				int32)
	DECLARE_EVENT_CLASS(RequestGetLotteryShop)
	DECLARE_EVENT_CLASS(RequestBuyShopProduct,					int32)
	DECLARE_EVENT_CLASS(RequestGetGeneralShop)
	DECLARE_EVENT_CLASS(RequestGetMagicShop)
	DECLARE_EVENT_CLASS(RequestRenewalMagicShop)
	DECLARE_EVENT_CLASS(RequestPurchaseMagicShop,					int32)
	DECLARE_EVENT_CLASS(RequestGetCollectionItem,				int32, int32)
	DECLARE_EVENT_CLASS(RequestRewardCollectionItem,			int32)
	DECLARE_EVENT_CLASS(RequestRewardCollectionSetItem,			int32, int32, int32)
	DECLARE_EVENT_CLASS(RequestGetMarketProduct)
	DECLARE_EVENT_CLASS(RequestPreparePurchase,					int32, const FString&)
	DECLARE_EVENT_CLASS(RequestVerifyPurchase,					const FString&, const FString&, const FString&, const FString&, bool, const FString&, float)
	DECLARE_EVENT_CLASS(RequestCancelPurchase,					const FString&, const FString&, int32)
	DECLARE_EVENT_CLASS(RequestFinishPurchase,					const FString&)
	DECLARE_EVENT_CLASS(RequestRaidResult,						const FString&, int32, bool, bool, bool)
	DECLARE_EVENT_CLASS(RequestDailyAttendance)
	DECLARE_EVENT_CLASS(RequestJoinGuildBattle)
	DECLARE_EVENT_CLASS(RequestGetGuildBattle)
	DECLARE_EVENT_CLASS(RequestStartGuildBattle,				int64)
	DECLARE_EVENT_CLASS(RequestFinishGuildBattle,				int64, const FString&, int32, int32)
	DECLARE_EVENT_CLASS(RequestSetGuildBattleEntry,				int32, int32, int32, int32, int32, int32, int32, int32)
	DECLARE_EVENT_CLASS(RequestGuildBattleTurnResult)
	DECLARE_EVENT_CLASS(RequestGuildBattleTurnReward)
	DECLARE_EVENT_CLASS(RequestGuildBattleSeasonReward)
	DECLARE_EVENT_CLASS(RequestGuildBattleHistory)
	DECLARE_EVENT_CLASS(RequestSetWingVisible,					int32, bool)
	DECLARE_EVENT_CLASS(RequestSetHelmetVisible,				int32, bool)
	DECLARE_EVENT_CLASS(RequestGetRaid)
	DECLARE_EVENT_CLASS(RequestRaidResurrection,				const FString&, int32)
	DECLARE_EVENT_CLASS(RequestResetAttendanceTime)
	DECLARE_EVENT_CLASS(RequestResetEventAttendance,			bool)
	DECLARE_EVENT_CLASS(RequestResetDailyPlayTimeRecord)
	DECLARE_EVENT_CLASS(RequestResetTeamMatchPoint)
	DECLARE_EVENT_CLASS(RequestChangeQuestId,					int32, int32)
	DECLARE_EVENT_CLASS(RequestChangeQuestCount,				int32, int32)
	DECLARE_EVENT_CLASS(RequestAssaultMatchmaking,				int32)
	DECLARE_EVENT_CLASS(RequestCancelAssaultMatchmaking,		const FString&)
	DECLARE_EVENT_CLASS(RequestAssaultResult,					const FString&, int32, bool, bool, b2network::B2AssaultBattleInfoPtr)
	DECLARE_EVENT_CLASS(RequestAssaultResurrection,				const FString&)
	DECLARE_EVENT_CLASS(RequestGetAssaultBattleStatus)
	DECLARE_EVENT_CLASS(RequestGetFriendRankings,               int32)
	DECLARE_EVENT_CLASS(RequestGetItemRandomOption)
	DECLARE_EVENT_CLASS(RequestGenerateItemRandomOption,        int64, int32)
	DECLARE_EVENT_CLASS(RequestApplyItemRandomOption,           int64)
	DECLARE_EVENT_CLASS(RequestDiscardItemRandomOption,			int64)
	DECLARE_EVENT_CLASS(RequestGetItemRandomQuality,			int64)
	DECLARE_EVENT_CLASS(RequestGenerateItemRandomQuality,		int64, int64)
	DECLARE_EVENT_CLASS(RequestApplyItemRandomQuality,			int64)
	DECLARE_EVENT_CLASS(RequestDiscardItemRandomQuality,		int64)
	DECLARE_EVENT_CLASS(RequestCheckRedDot,						const TArray<int32>&)
	DECLARE_EVENT_CLASS(RequestCheckChargePoints,				bool, bool, bool)
	DECLARE_EVENT_CLASS(RequestIncreaseDarkCrystalPaid,         int32)
	DECLARE_EVENT_CLASS(RequestCheckPvPMatchPointCharge)
	DECLARE_EVENT_CLASS(RequestCheckTeamMatchPointCharge)
	DECLARE_EVENT_CLASS(RequestFindAccount,						const TArray<b2network::B2FindAccountQueryPtr>&)
	DECLARE_EVENT_CLASS(RequestModifyItemRandomOption,			int64, int32, int32, float)
	DECLARE_EVENT_CLASS(RequestModifyItemNewFlag,				int32, int32)
	DECLARE_EVENT_CLASS(RequestModifyCostumeNewFlag,			int32, int32)
    DECLARE_EVENT_CLASS(RequestStartRaid,						int32)
	DECLARE_EVENT_CLASS(RequestGetContentsOpenStatus,               int32)
	DECLARE_EVENT_CLASS(RequestGetDuelRewardBoxInfo,				int32)
	DECLARE_EVENT_CLASS(RequestGetDuelRewardBoxGainableList,		int32, int32)
	DECLARE_EVENT_CLASS(RequestOpenDuelRewardBox,					int32)
	DECLARE_EVENT_CLASS(RequestReceiveAssaultMvpReward)
	DECLARE_EVENT_CLASS(RequestEventAttendance,					int32)
	DECLARE_EVENT_CLASS(RequestBeginnerAttendance)
	DECLARE_EVENT_CLASS(RequestUpdateDailyPlayTime,				int32)
	DECLARE_EVENT_CLASS(RequestReceiveDailyPlayTimeReward)

	DECLARE_EVENT_CLASS(RequestAskGuildSupport,					int32)
	DECLARE_EVENT_CLASS(RequestGuildSupport,					int64, int64, int32)
	DECLARE_EVENT_CLASS(RequestGetGuildChat,					int32)

	DECLARE_EVENT_CLASS(RequestGetAccountAether,				int32)
	DECLARE_EVENT_CLASS(RequestDismantleAethers,				const TArray<int64>&)
	DECLARE_EVENT_CLASS(RequestMountAethers,					const TArray<int64>&, int32)
	DECLARE_EVENT_CLASS(RequestUnmountAethers,					const TArray<int64>&, int32)
	DECLARE_EVENT_CLASS(RequestLockAethers,						const TArray<int64>&)
	DECLARE_EVENT_CLASS(RequestUnlockAethers,					const TArray<int64>&)
	DECLARE_EVENT_CLASS(RequestExtendAetherInventory,			int32)
	DECLARE_EVENT_CLASS(RequestEnhanceAether,					int64)
	DECLARE_EVENT_CLASS(RequestModifyAetherNewFlag,				int32)
	DECLARE_EVENT_CLASS(RequestSelectAetherDefenseOption,		int32, int32)
	DECLARE_EVENT_CLASS(RequestSelectAetherUnitySkillOption,	int32, int32)
	DECLARE_EVENT_CLASS(RequestSellAethers,						const TArray<int64>&)
	DECLARE_EVENT_CLASS(RequestGetUnitySkillMission,			int32)
	DECLARE_EVENT_CLASS(RequestReceiveUnitySkillReward,			int32, int32)
	DECLARE_EVENT_CLASS(RequestAwakenUnitySkillMission,			int32, int32)
	DECLARE_EVENT_CLASS(RequestAwakenUnitySkill,				int32)
	DECLARE_EVENT_CLASS(RequestGetDuelModeInfo)
	DECLARE_EVENT_CLASS(RequestGetChallengeModeInfo)
	DECLARE_EVENT_CLASS(RequestReceiveRestReward,			    int32, bool)
	DECLARE_EVENT_CLASS(RequestCheckModeOpen)
	DECLARE_EVENT_CLASS(RequestGuildDonation,					int32, int32)
	DECLARE_EVENT_CLASS(RequestGetHallOfFame,					int32, bool)
	DECLARE_EVENT_CLASS(RequestPraiseTargetRanker,				int32, int64, int32)

	DECLARE_EVENT_CLASS(RequestGetTutorialProgress,                 )
	DECLARE_EVENT_CLASS(RequestSetTutorialProgress,                 )
	DECLARE_EVENT_CLASS(RequestUpdateTutorialProgress,              )
	DECLARE_EVENT_CLASS(RequestSkipTutorialProgress,                )
	DECLARE_EVENT_CLASS(RequestDrawTutorialItem,                    int32)
	DECLARE_EVENT_CLASS(RequestPrepareTutorial,                     int32)
	DECLARE_EVENT_CLASS(RequestGiveTutorialReward,                  )
	DECLARE_EVENT_CLASS(RequestCheckReachPower,                 const TArray<b2network::B2CharacterPowerPtr>&)
	DECLARE_EVENT_CLASS(RequestTrackingPowerDetail,				int32, int32, int32, const TArray<b2network::B2CharacterPowerSpecificPtr>&)
	DECLARE_EVENT_CLASS(RequestKakaoMessageProcessing,			const FString&)
	DECLARE_EVENT_CLASS(RequestKakaoCouponUse,					const FString&)
	DECLARE_EVENT_CLASS(RequestKakaoAccountConversionPrepare,	const FString&)
	DECLARE_EVENT_CLASS(RequestKakaoAccountConversionComplete,	const FString&)
	DECLARE_EVENT_CLASS(RequestSkipMatchTutorial,				int32)
	DECLARE_EVENT_CLASS(RequestGetEvent)
	DECLARE_EVENT_CLASS(RequestReceivePointEventReward,			int32, int32)
	DECLARE_EVENT_CLASS(RequestReceiveLevelUpEventReward,		int32, int32)
	DECLARE_EVENT_CLASS(RequestReceiveStageClearEventReward,	int32, int32)
	DECLARE_EVENT_CLASS(RequestGetSeasonMission,				)
	DECLARE_EVENT_CLASS(RequestRewardSeasonMission,				int32, int32, int32)
	DECLARE_EVENT_CLASS(RequestAttendSeasonMission				)
	DECLARE_EVENT_CLASS(RequestServerCmd,						const FString&)
	DECLARE_EVENT_CLASS(RequestSetDebugMode,					bool)
	DECLARE_EVENT_CLASS(RequestSetRoomDebugMode,				bool)
	DECLARE_EVENT_CLASS(RequestBuyHotTimeBuff,					int32)
	DECLARE_EVENT_CLASS(RequestRewardFlatRatePackageBonus		)
	DECLARE_EVENT_CLASS(RequestGetPackageShop					)
	DECLARE_EVENT_CLASS(RequestGetPeriodPackageState			)
	DECLARE_EVENT_CLASS(RequestRewardLevelUpPackage,			int32, int32, int32)
	DECLARE_EVENT_CLASS(RequestRewardReachLevelPackage,			int32)
	DECLARE_EVENT_CLASS(RequestGiveUpQuest,						int32)
	DECLARE_EVENT_CLASS(RequestGetContentsModeState,			int32)
	DECLARE_EVENT_CLASS(RequestRewardPointShopEvent,			int32, int32, int32)
	DECLARE_EVENT_CLASS(RequestTrace,							const FString&)
	DECLARE_EVENT_CLASS(RequestReportUser,						int64, int32, int32, const FString&)
	DECLARE_EVENT_CLASS(RequestBlockChat,						int64)
	DECLARE_EVENT_CLASS(RequestUnblockChat,						int64)
	DECLARE_EVENT_CLASS(RequestGetBlockChatList)
	DECLARE_EVENT_CLASS(RequestClientStateReport,				const FString&, const FString&, const FString&, const FString&)
	DECLARE_EVENT_CLASS(RequestRewardTenLotteryEvent,			int32, int32)
	DECLARE_EVENT_CLASS(RequestRewardSpendGemEvent,				int32, int32)
	DECLARE_EVENT_CLASS(RequestReceiveGemPurchaseEventReward,	int32, int32)
	DECLARE_EVENT_CLASS(RequestRewardTenLotterySavingsEvent,	int32)
	DECLARE_EVENT_CLASS(RequestInvitation,					    const FString&, const FString&)
	DECLARE_EVENT_CLASS(RequestAcceptInvitation,			    const int32, const FString&, const FString&, const FString&, b2network::B2RoomLocationPtr)
	DECLARE_EVENT_CLASS(RequestDeclineInvitation,			    const int32, const FString&, const FString&, const FString&)
	DECLARE_EVENT_CLASS(RequestRollDiceEvent,					const int32, const bool)
	DECLARE_EVENT_CLASS(RequestBuyDiceEventPoint,				const int32)
	DECLARE_EVENT_CLASS(RequestRewardDiceEventMileage,			const int32, const int32)

	DECLARE_EVENT_CLASS(RequestGetAccountCostume,				int32, int32)
	DECLARE_EVENT_CLASS(RequestEquipCostume,					const TArray<int64>&)
	DECLARE_EVENT_CLASS(RequestUnequipCostume,					const TArray<int64>&)
	DECLARE_EVENT_CLASS(RequestEnhanceCostume,					int64)
	DECLARE_EVENT_CLASS(RequestDismantleCostumes,				const TArray<int64>&)
	DECLARE_EVENT_CLASS(RequestLockCostumes,					const TArray<int64>&)
	DECLARE_EVENT_CLASS(RequestUnlockCostumes,					const TArray<int64>&)
	DECLARE_EVENT_CLASS(RequestGetCostumeShop)
	DECLARE_EVENT_CLASS(RequestPurchaseCostume,					int32)
	DECLARE_EVENT_CLASS(RequestSetCostumeVisible,				int32, int32, bool)

	// totem
	DECLARE_EVENT_CLASS(RequestGetAccountTotem)
	DECLARE_EVENT_CLASS(RequestEquipTotems,						const TArray<int64>&, int32)
	DECLARE_EVENT_CLASS(RequestUnequipTotems,					const TArray<int64>&)
	DECLARE_EVENT_CLASS(RequestLockTotems,						const TArray<int64>&)
	DECLARE_EVENT_CLASS(RequestUnlockTotems,					const TArray<int64>&)
	DECLARE_EVENT_CLASS(RequestSellTotems,						const TArray<int64>&)
	DECLARE_EVENT_CLASS(RequestDismantleTotems,					const TArray<int64>&)
	DECLARE_EVENT_CLASS(RequestRefineTotem,						int64, int32, int32)
	DECLARE_EVENT_CLASS(RequestModifyTotemNewFlag)
	DECLARE_EVENT_CLASS(RequestAddTotemToInventory,				int32)

	//ItemForge
	DECLARE_EVENT_CLASS(RequestItemForgeList)
	DECLARE_EVENT_CLASS(RequestItemForge,						int64, int64, int64, int64, int64, int64, int64, int64, int64, int64, int64, int64)

	//SealBox
	DECLARE_EVENT_CLASS(RequestUnsealBox,						int64, int32, int64)


	// REPLACEMENT POINT: INTERNAL HEADER REQUEST
	// NEVER DELETE LINE ABOVE

	// notifies
    DECLARE_EVENT_CLASS(RoomHeartbeatNotify)
    DECLARE_EVENT_CLASS(RoomParticipantJoinNotity,				const FString&, b2network::B2RoomParticipantPtr)
    DECLARE_EVENT_CLASS(RoomParticipantLeaveNotity,				const FString&, b2network::B2RoomParticipantPtr)
    DECLARE_EVENT_CLASS(RoomMessageNotify,						const FString&, b2network::B2RoomParticipantPtr, const FString&)
    DECLARE_EVENT_CLASS(RoomHostChangedNotify,                  const FString&, int32, int32)
    DECLARE_EVENT_CLASS(RoomPropertyUpdatedNotify,              const FString&, const TArray<b2network::B2RoomPropertyPtr>&)
	DECLARE_EVENT_CLASS(ChatMessageNotify,						b2network::FB2MessageInfoChatNotifyPtr)
	DECLARE_EVENT_CLASS(GuildChatMessageNotify,					b2network::FB2MessageInfoGuildChatNotifyPtr)
	DECLARE_EVENT_CLASS(QuestAlarmNotify,						int32, b2network::B2QuestInfoPtr, const TArray<b2network::B2RewardPtr>)
	DECLARE_EVENT_CLASS(MissionAlarmNotify,						int32, int32)
    DECLARE_EVENT_CLASS(InvitationNotify,					    int32, const FString&, const FString&, b2network::B2RoomLocationPtr)
    DECLARE_EVENT_CLASS(AcceptInvitationNotify,				    int32, const FString&, const FString&, b2network::B2RoomLocationPtr)
    DECLARE_EVENT_CLASS(DeclineInvitationNotify,				int32, const FString&, const FString&)
	DECLARE_EVENT_CLASS(RaidInvitationNotify,                   const FString&, const FString&, b2network::B2RoomLocationPtr, int32, int32)
    DECLARE_EVENT_CLASS(AdminMessageNotify,                     const FString&, int32)
	DECLARE_EVENT_CLASS(ContentsModeStateNotify,				int32, int32, int32)

	// commands
	DECLARE_EVENT_CLASS(SendRoomMessage,						const FString&, int32, const FString&)
	DECLARE_EVENT_CLASS(SendChatMessage,						int32, const FString&, int32, const FString&, int32)

    // events
    DECLARE_EVENT_CLASS(ServiceConnectingEvent)
    DECLARE_EVENT_CLASS(ServiceConnectedEvent)
    DECLARE_EVENT_CLASS(ServiceNotAvailableEvent,				int32)
    DECLARE_EVENT_CLASS(ServerAddressErrorEvent)
    DECLARE_EVENT_CLASS(RequireNicknameEvent)
	DECLARE_EVENT_CLASS(RequireUpdateProtocolEvent)
	DECLARE_EVENT_CLASS(RequireUpdateAppVersionEvent)
	DECLARE_EVENT_CLASS(ServerTimeSyncEvent,					int64)
	DECLARE_EVENT_CLASS(ChannelDisconnectedEvent,				int32)
	DECLARE_EVENT_CLASS(SessionClosedNotify, int32)
	DECLARE_EVENT_CLASS(DisconnectReasonLogEvent, int32);
}
